/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.ErrorDescription
import io.swagger.client.model.ReferenceDataItem
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object UtilitiesApi {

  /**
   *  Reference data resource to be used to retrive lists of pseudo-enums from the database. 
   * 
   * Expected answers:
   *   code 200 : ReferenceDataItem (The search result)
   *              Headers :
   *                api-business-govt-nz-Request-Id - MBIE Request id header
   *                api-business-govt-nz-Correlation-Id - MBIE Correlation id header
   *                date - Response parameter. Date/time the response was generated (in Greenwich mean time).
   *                service-version - The minor version of the API.
   *   code 400 : ErrorDescription (The combination of search enquiry parameters is invalid.)
   *   code 401 :  (The requester is not authenticated.)
   *   code 403 :  (The requester is not authorised for this operation.)
   *   code 500 : ErrorDescription (An unexpected internal server error occurred.)
   * 
   * Available security schemes:
   *   jwt (apiKey)
   * 
   * @param referenceDataType * The reference data list to be retreived 
   * @param page The page in the collection to return. Default is page 1.
   * @param pageSize The requested number of items to include in each page returned. Default is 20. 
   * @param sortOrder The order to sort the collection in. Can be &#39;asc&#39; or &#39;desc&#39;.
   * @param sortBy The property to sort the collection by.
   */
  def getReferenceData(referenceDataType: String, page: Option[Int], pageSize: Option[Int], sortOrder: Option[String], sortBy: Option[String])(implicit apiKey: ApiKeyValue): ApiRequest[ReferenceDataItem] =
    ApiRequest[ReferenceDataItem](ApiMethods.GET, "https://virtserver.swaggerhub.com/apis/OASIS4-development/oasis4/1.4.13", "/references", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withQueryParam("reference-data-type", referenceDataType)
      .withQueryParam("page", page)
      .withQueryParam("page-size", pageSize)
      .withQueryParam("sort-order", sortOrder)
      .withQueryParam("sort-by", sortBy)
      .withSuccessResponse[ReferenceDataItem](200)
      .withErrorResponse[ErrorDescription](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](403)
      .withErrorResponse[ErrorDescription](500)
      
  object GetReferenceDataHeaders { 
    def apiBusinessGovtNzRequestId(r: ApiReturnWithHeaders) = r.getStringHeader("api-business-govt-nz-Request-Id")
    def apiBusinessGovtNzCorrelationId(r: ApiReturnWithHeaders) = r.getStringHeader("api-business-govt-nz-Correlation-Id")
    def date(r: ApiReturnWithHeaders) = r.getDateTimeHeader("date")
    def serviceVersion(r: ApiReturnWithHeaders) = r.getStringHeader("service-version")
  }


}

