/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AddressSearchResult (
  /* the primary identifier for the address record  */
  addressId: Option[Double],
  /* flag to indicate if the record is 'current' and as such, in use for the contact  */
  isCurrent: Option[Boolean],
  /* Enum of the valid contact address types  */
  addressType: Option[AddressSearchResultEnums.AddressType],
  /* The date that this address is valid from.  */
  validFrom: Option[Date],
  /* the date after wich this address should be considered invalid  */
  validTo: Option[String],
  /* A concatenation into a single sting of the phone number, email, postal or physical address */
  polymorhpicAddressValue: Option[String],
  addressRecord: Option[Link]
) extends ApiModel

object AddressSearchResultEnums {

  type AddressType = AddressType.Value
  object AddressType extends Enumeration {
    val PHY = Value("PHY")
    val TEL = Value("TEL")
    val EML = Value("EML")
    val PST = Value("PST")
  }

}

