/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ClaimEvidenceRecord (
  /* The channel from which the claim was recieved - DRM (aka online) POS (aka Postal) or FAX.  */
  supplyType: Option[String],
  /* Primary key  */
  id: Option[Double],
  /* The claim to which the price of evidence belongs / supports.  */
  claimId: Option[Double],
  /* The file name chosen by the submitter.  */
  filename: Option[String],
  /* The primary key for the object in the DRM micro-service  */
  drmId: Option[Double],
  /* The user that last updated the evidence record  */
  lastUpdatedBy: Option[String],
  /* The username of the user that last updated the evidence record  */
  lastUpdatedName: Option[String],
  /* The date that the evidence record was last updated.  */
  lastUpdated: Option[Date],
  /* The version number of the evidence record  */
  version: Option[Double]
) extends ApiModel


