/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ClaimRegistrationSearchResult (
  /* Concatenation of estate number and estate name */
  estate: Option[String],
  /* The name of the creditor. Where the onBehalfOf field is populated, this feild is to be contactenated  */
  creditorName: Option[String],
  /* The name of the individual that created the claim. */
  createdBy: Option[String],
  /* The date the claim was created. */
  createdOn: Option[Date],
  /* Boolean indicating whether the claim has a joint estate. */
  jointEstate: Option[Boolean],
  /* Boolean indicating whether the claim is an SIO claim */
  sio: Option[Boolean],
  links: Option[Link]
) extends ApiModel


