/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ClaimRegistrationRecord (
  /* This should be used concatenated with createdBy when displaying the claim (NEW FIELD)  */
  claimOnBehalfOf: Option[String],
  /* The email address of the claimant.  */
  creditorEmail: Option[String],
  /* The primary identifier of a Claim Registration.   */
  claimRegistrationId: Option[Double],
  /* The type of claim made  */
  transactionCode: Option[String],
  /* The creditor's reference to be used for this Claim Registration.   */
  creditorReference: Option[String],
  /* Notification options - boolean preference for notification frequency.  */
  notficationThreeMonthly: Option[Boolean],
  /* Notificationoptions - boolean preference for notification frequency.  */
  notficationSixMonthly: Option[Boolean],
  /* Unknown  */
  estateAdminComplete: Option[Boolean],
  /* Unknown  */
  estateAdminReopened: Option[Boolean],
  /* Boolean used to determine the ultimate claim type & priority.   */
  outstandingAmountSecured: Option[Boolean],
  /* A financing statement contains information about a security interest. The actual security agreement is not registered on PPSR. In its place, a notice of this agreement is posted on PPSR by registering a financing statement. Registering a financing statement is one way of protecting a security interest and determining priority.  */
  ppsrFinancingStatementRegistrationNumber: Option[String],
  /* Notificationoptions - boolean preference for alert when a large claim is filed.  */
  notificationFilingClaimLargeClaim: Option[Boolean],
  /* Adjudication and Applicationcosts awarded by the courts. Boolean used to determine the ultimate claim type & priority.   */
  adjAppCosts: Option[Boolean],
  /* Boolean used to determine the ultimate claim type & priority.   */
  wagesHolidayPay: Option[Boolean],
  /* Boolean used to determine the claim type & priority.   */
  unpaidTaxesLevies: Option[Boolean],
  /* Boolean used to determine the claim type and priority.   */
  outstandingAmountNotSecured: Option[Boolean],
  /* Boolean indicating whether the claim is subject to court action, used to determine the claim type and priority.   */
  subjectToCourtActionYn: Option[Boolean],
  /* The userID that created the Claim Registration.   */
  createdBy: Option[String],
  /* The version number of the Claim Registration.   */
  version: Option[Double],
  /* If the claim is not filed by the actual claimant, the name of the person completing the application.  */
  personEnteringApp: Option[String],
  /* Unknown. Appears to be roles, But also free text. Hard to say where this comes from.   */
  designation: Option[String],
  /* The amount claimed in relation to any adjudication / application costs for the estate   */
  adjAppCostsAmountClaimed: Option[Double],
  /* The amount claimed, in words. Used as a manual checksum.   ___ * PROPOSED TO REMOVE THIS  ___  */
  adjAppCostsAmountClaimedInWords: Option[String],
  /* Enum - how the evidence was provided. POS, FAX or DRM. Relating to Postal, Online attachment or Fax evidence.   */
  appEvidenceCode: Option[ClaimRegistrationRecordEnums.AppEvidenceCode],
  /*  */
  wagesAmountClaimed: Option[Double],
  /*  */
  wagesAmountInWords: Option[String],
  /* The start for the time period for which wages are claimed.   */
  wagesFromdate: Option[Date],
  /* The end date for the time period for which wages are claimed.   */
  wagesTodate: Option[Date],
  /* Description of the circumstances & particulars for the wages claim.   */
  wagesDescription: Option[String],
  /* Enum:   */
  wagesEvidenceCode: Option[ClaimRegistrationRecordEnums.WagesEvidenceCode],
  /* The amount claimed in relation to wages.   */
  taxesAmountClaimed: Option[Double],
  /* The amount claimed in relation to taxes owed, in words.   */
  taxesAmountInWords: Option[String],
  /* The GST content of the taxes owed.   */
  taxesGstContent: Option[Double],
  /* The start date to which the tax claim relates.   */
  taxesFromdate: Option[Date],
  /* The end date to which the tax claim relates.   */
  taxesTodate: Option[Date],
  /* A description of the Tax claim.   */
  taxesDescription: Option[String],
  /*  */
  taxesEvidenceCode: Option[String],
  /* The amount claimed for other types of debt.   */
  outAmountClaimed: Option[Double],
  /* T   */
  outAmountInWords: Option[String],
  /* The GST content of claims under other in the Claim Registration.   */
  outGstContent: Option[Double],
  /* The start date for claims under other.   */
  outFromdate: Option[Date],
  /* The end date for claims under other.   */
  outTodate: Option[Date],
  /* Description of claims under other.   */
  outDescription: Option[String],
  /* Enum   */
  outEvidenceCode: Option[String],
  /* The value of securities claimed as part of the application.   */
  secValue: Option[Double],
  /*  */
  secValueInWords: Option[String],
  /* Description of the securities claimed in the application.   */
  secDescription: Option[String],
  /*  */
  secEvidenceCode: Option[String],
  /* Description of any court actions relation to any of the claims in the application.   */
  courtActionDescription: Option[String],
  /*  */
  coutActionCode: Option[String],
  /* The link to the evidence of court action supplied with the application.   */
  courtActionEvidence: Option[String],
  /* Boolean indicating whether the application includes court awarded interest or interest agreed in a contract. Mandatory .  */
  claimIncludeInterestYn: Option[Boolean],
  /* Enum   */
  interestEvidenceCode: Option[String],
  /* Currency code for??   */
  curCode: Option[String],
  /* Currency code for claims relating to tax.   */
  curCodeTaxes: Option[String],
  /* Currency code for amounts relating to securities claimed.   */
  curCodeSecurity: Option[String],
  /* Currency code relating to amounts clamed under other.   */
  curCodeOutstanding: Option[String],
  /* The unique contact ID relating to the account that created the claim.   */
  cttId: Option[Double],
  /* The key creditor id - MAP AS A MULTIPLE TO ABOVE RECORD   */
  orgId: Option[Double],
  /* The currency code for adjudicated or application costs.   */
  codeApp: Option[String]
) extends ApiModel

object ClaimRegistrationRecordEnums {

  type AppEvidenceCode = AppEvidenceCode.Value
  type WagesEvidenceCode = WagesEvidenceCode.Value
  object AppEvidenceCode extends Enumeration {
    val FAX = Value("FAX")
    val POS = Value("POS")
    val DRM = Value("DRM")
  }

  object WagesEvidenceCode extends Enumeration {
    val FAX = Value("FAX")
    val POS = Value("POS")
    val DRM = Value("DRM")
  }

}

