/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ContactPaymentDetailRecord (
  /*  */
  contactPaymentDetailId: Option[Double],
  /*  */
  contactPaymentDetailCttId: Option[Double],
  /*  */
  contactPaymentDetailType: Option[String],
  /*  */
  contactPaymentDetailVersion: Option[Double],
  /*  */
  contactPaymentDetailCreated: Option[Date],
  /*  */
  contactPaymentDetailCreatedBy: Option[String],
  /*  */
  contactPaymentDetailCreatedName: Option[String],
  /*  */
  contactPaymentDetailLastUpdated: Option[Date],
  /*  */
  contactPaymentDetailLastUpdatedBy: Option[String],
  /*  */
  contactPaymentDetailLastUpdatedName: Option[String],
  /*  */
  contactPaymentDetailStatus: Option[String],
  /*  */
  contactPaymentDetailAccountName: Option[String],
  /*  */
  contactPaymentDetailBank: Option[String],
  /*  */
  contactPaymentDetailBranch: Option[String],
  /*  */
  contactPaymentDetailAccount: Option[String],
  /*  */
  contactPaymentDetailSuffix: Option[String],
  /*  */
  contactPaymentDetailEnteredBy: Option[String],
  /*  */
  contactPaymentDetailVerifiedBy: Option[String],
  /*  */
  contactPaymentDetailVerified: Option[String],
  /*  */
  contactPaymentDetailNotes: Option[String]
) extends ApiModel


