/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ContactSearchResult (
  /* The unique identifier for a contact record.   */
  contactId: Option[Int],
  /*  */
  firstName: Option[String],
  /*  */
  lastName: Option[String],
  /*  */
  middleNames: Option[String],
  /*  */
  titleCode: Option[String],
  /* The 'main' contact name.   */
  contactName: Option[Int],
  /* The unique identifier for a contact record.   */
  contactAliases: Option[Seq[NameRecord]],
  /* The 'main' contact address. */
  contactAddress: Option[Int],
  /* Array of address records. */
  contactAddresses: Option[Seq[Address]],
  /* The date that the contact record was created.   */
  created: Option[String],
  /* The 'type' of contact indicating whther human  or not. */
  `type`: Option[ContactSearchResultEnums.&#x60;Type&#x60;],
  /* Link to the actual contact record. */
  contactRecord: Option[Link]
) extends ApiModel

object ContactSearchResultEnums {

  type &#x60;Type&#x60; = &#x60;Type&#x60;.Value
  object &#x60;Type&#x60; extends Enumeration {
    val Contact = Value("Contact")
    val Branch = Value("Branch")
    val Organisation = Value("Organisation")
  }

}

