/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CreditorClaimRecord (
  /* The primary key of the claim & claim id used by the estate   */
  claimId: Option[Double],
  /* The name of the actual claimant where the claim is not beng made by the actual claimant. This should be used concatenated with createdBy when displaying the claim (NEW FIELD)  */
  claimOnBehalfOf: Option[String],
  /* The claim registration that generated the claim.  */
  claimRegistrationId: Option[String],
  /* A financing statement contains information about a security interest. The actual security agreement is not registered on PPSR. In its place, a notice of this agreement is posted on PPSR by registering a financing statement. Registering a financing statement is one way of protecting a security interest and determining priority.  */
  ppsrFinancingStatementRegistrationNumber: Option[String],
  /* Needs to be captured in a new field coming from ONC_POTENTIAL_ONLINE_CLAIMS  */
  claimRegistrationType: Option[CreditorClaimRecordEnums.ClaimRegistrationType],
  /* The type of claim made  */
  transactionCode: Option[String],
  /* The account that created the claim - could be created from the initial statement of affairs, the insolvency officer or the creditor (or agent).   */
  claimCreatedBy: Option[String],
  /* The name of the person creating the claim   */
  claimCreatedName: Option[String],
  /* The type of claim - used in the process to determine priority  Currently one of..    - Bankrupt    - Chattel Security    - Contributory    - Debenture interest    - Deferred debt creditor    - Fixed debenture holder    - Floating debenture holder    - Instrument by way of security    - Mortgage    - Official Assignee basic income    - Other creditor with/without POD    - Petitioning creditors costs    - Preferential unsecured creditor    - Security Interest    - Supporting Creditor Costs    - Unsecured creditor with POD  */
  claimType: Option[String],
  /* The date that the claim was created   */
  claimCreated: Option[Date],
  /* The person (user account) that last update the claim record.   */
  claimLastUpdatedBy: Option[String],
  /* The user name of the person who last update the claim.   */
  claimLastUpdatedName: Option[String],
  /* The dateTime the claim was last updated.   */
  claimLastUpdated: Option[DateTime],
  /* The version (aka revision) of the claim.   */
  claimVersion: Option[Double],
  /* The date on which the (current) status for the claim became current.   */
  claimStatusdate: Option[Date],
  /* The reference supplied by the creditor for the claim. Not necessarily unique (many claims may well have the same reference).   */
  claimCreditorReference: Option[String],
  /* The value of the claim as notified by the debtor.   */
  claimNotifiedValue: Option[Double],
  /* The value to be paid on the claim by the estate.   */
  claimValue: Option[Double],
  /* Boolean indicating whether the claim is subject to court action, used to determine the claim type and priority.   */
  subjectToCourtActionYn: Option[Boolean],
  /* Unknown   */
  claimContractInterestYn: Option[Boolean],
  /* The IRD number of the claimant   */
  claimIrdNumber: Option[String],
  /* If a claim was withdrawn (can only be done as the creditor) the reason for this action.   */
  claimWithdrawnReason: Option[String],
  /* The user account that withdrew the claim.   */
  claimWithdrawnBy: Option[String],
  /* The name of the user that withdrew the claim.   */
  claimWithdrawnByName: Option[String],
  /* The data the creditor withdrew the claim.   */
  claimWithdrawndate: Option[Date],
  /* The currency (code) if the claim. Loosely mapped to the ISO4217 country codes. Currently updated infrequently   */
  claimCurCode: Option[String],
  /* Unknown   */
  claimWtcId: Option[Double],
  /* Unknown   */
  creditorId: Option[Double],
  /* Unknown   */
  organisationId: Option[Double],
  /* Unknown   */
  claimOncId: Option[Double],
  claimStatus: Option[CreditorClaimRecordEnums.ClaimStatus],
  links: Option[Seq[Link]]
) extends ApiModel

object CreditorClaimRecordEnums {

  type ClaimRegistrationType = ClaimRegistrationType.Value
  type ClaimStatus = ClaimStatus.Value
  object ClaimRegistrationType extends Enumeration {
    val CourtAwardedYouAdjudicationapplicationCosts = Value("Court awarded you adjudication/application costs")
    val ClaimForWagesHolidayPayOrRedundancy = Value("Claim for wages, holiday pay or redundancy")
    val Other = Value("Other")
    val SecuredDebt = Value("Secured debt")
    val CourtAction = Value("Court action")
    val InterestAwardedByACourtOrAgreedToInAContract = Value("Interest awarded by a Court or agreed to in a contract")
  }

  object ClaimStatus extends Enumeration {
    val Errored = Value("Errored")
    val Admitted = Value("Admitted")
    val Potential = Value("Potential")
    val Received = Value("Received")
    val Withdrawn = Value("Withdrawn")
    val Rejected = Value("Rejected")
    val Suspended = Value("Suspended")
    val Duplicate = Value("Duplicate")
  }

}

