/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class FileMetadataRecord (
  /*  */
  fodId: Option[Double],
  /*  */
  fodFolId: Option[Double],
  /*  */
  fodDocumentStorageId: Option[Double],
  /*  */
  fodFilename: Option[String],
  /*  */
  fodDescription: Option[String],
  /*  */
  fodLastUpdatedBy: Option[String],
  /*  */
  fodLastUpdatedName: Option[String],
  /*  */
  fodLastUpdated: Option[Date],
  /*  */
  fodVersion: Option[Double],
  /*  */
  fodLinkedFrom: Option[String],
  /*  */
  fodLinkedFromFolioId: Option[Double]
) extends ApiModel


