/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class FolioSearchResult (
  /* The Folio ID contactenated with the sequence */
  item: Option[String],
  /* Giraffe Bank Unsecured creditor with POD */
  `type`: Option[FolioSearchResultEnums.&#x60;Type&#x60;],
  links: Option[FolioRecord]
) extends ApiModel

object FolioSearchResultEnums {

  type &#x60;Type&#x60; = &#x60;Type&#x60;.Value
  object &#x60;Type&#x60; extends Enumeration {
    val Folio = Value("Folio")
    val Claim = Value("Claim")
  }

}

