/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Link (
  /* The rel attribute specifies the relationship between the current resource and the linked resource.  */
  rel: String,
  /* Specifies the URL of the resource the link goes to */
  href: String,
  /* Specifies the HTTP method used */
  method: LinkEnums.Method
) extends ApiModel

object LinkEnums {

  type Method = Method.Value
  object Method extends Enumeration {
    val HEAD = Value("HEAD")
    val GET = Value("GET")
    val PUT = Value("PUT")
    val POST = Value("POST")
    val PATCH = Value("PATCH")
    val DELETE = Value("DELETE")
  }

}

