/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class MaintianClaimRecord (
  /* The status of the claim   */
  claimStatus: Option[MaintianClaimRecordEnums.ClaimStatus],
  /* Unknown   */
  claimManualSourceCode: Option[String],
  /* Boolean indicating whether claim is being appealed in the courts.   */
  claimUnderAppeal: Option[Boolean],
  /* The (payment) priority of the claim (once claim becomes part of the estate).   */
  claimPriority: Option[Double],
  /* The reference supplied by the creditor for the claim. Not necessarily unique (many claims may well have the same reference).   ### NOTE If longer than 12 digits it can't appear on the statement  */
  claimCreditorReference: Option[String],
  /* The value of the claim as notified by the debtor.   */
  claimNotifiedValue: Option[Double],
  /* The value to be paid on the claim by the estate.   */
  claimValue: Option[Double],
  /* Unknown, mandatory   */
  claimContractInterestYn: Option[Boolean],
  /* Unknown, mandatory  */
  claimValueTbaYn: Option[Boolean],
  /* The IRD number of the claimant   */
  claimIrdNumber: Option[String],
  /* Does the claim include GST for the Official Assignee?   */
  claimIncludeOaGstYn: Option[Boolean],
  /* The calculated amount of GST that needs to be paid on the claim for the OA.   */
  claimOaGstAmount: Option[Double],
  /* The tax rate payable on a claim for wages.   */
  claimWagesTaxRate: Option[Double],
  /* Comments from the case officer(s) about the claim   */
  claimComments: Option[String],
  /* The date that the case officer was made aware of the claim??   */
  claimItsAwaredate: Option[Date],
  /* The date the claim was lodged with ITS.   */
  claimLodgedWithItsdate: Option[DateTime],
  /* Unknown   */
  claimAdmittedValue: Option[Double],
  /* The currency (code) if the claim. Loosely mapped to the ISO4217 country codes. Currently updated infrequently   */
  claimCurCode: Option[String],
  /* Unknown   */
  claimWtcId: Option[Double],
  /* the id of the creditor record   */
  creditorId: Option[Double],
  /* The organisation ID that the claim belongs to   */
  organisationId: Option[Double],
  /* Comment from insolvency officer when changing claim meta-data   */
  claimReasonForChange: Option[String],
  /* Boolean flag recoding if alert has been sent.   */
  claimLargeClmFiledAlertSent: Option[String],
  /* Flag recording if a creditor report has been sent.   */
  claimCredRptSent: Option[String],
  links: Option[Seq[Link]]
) extends ApiModel

object MaintianClaimRecordEnums {

  type ClaimStatus = ClaimStatus.Value
  object ClaimStatus extends Enumeration {
    val Errored = Value("Errored")
    val Admitted = Value("Admitted")
    val Potential = Value("Potential")
    val Received = Value("Received")
    val Withdrawn = Value("Withdrawn")
    val Rejected = Value("Rejected")
    val Suspended = Value("Suspended")
    val Duplicate = Value("Duplicate")
  }

}

