/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class OrganisationSearchResult (
  /* The unique organisation number. */
  organisationId: Option[String],
  /* The date that the organisation was created */
  organisaitonCreatedDate: Option[Date],
  /* The name of the person that created the organisation record.  */
  createdName: Option[String],
  /* Unknown */
  organisationName: Option[String],
  /* Boolean indicating whether the organisation is trusted or not. */
  organisationTrustedYn: Option[Boolean],
  /*  */
  bankYn: Option[Boolean],
  /* mandatory */
  securedYn: Option[Boolean],
  /*  */
  creditCardYn: Option[Boolean],
  /* mandatory */
  inUseYn: Option[Boolean],
  /*  */
  mainContactYn: Option[Boolean],
  /*  */
  trusted: Option[String],
  /*  */
  bank: Option[String],
  /*  */
  secured: Option[String],
  /*  */
  ceditCard: Option[String],
  /*  */
  inUse: Option[String],
  /*  */
  mainContact: Option[String],
  organisationRecord: Option[Link]
) extends ApiModel


