/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TaxNumbers (
  /* The primary key for the tax number  */
  taxNumberId: Option[Double],
  /* The type of tax number - GST or IRD  */
  taxNumberType: Option[String],
  /* The (current) version of the record  */
  taxNumberVersion: Option[Double],
  /* The date the record was created  */
  taxNumberCreated: Option[String],
  /* The user that created the record  */
  taxNumberCreatedBy: Option[String],
  /* The name of the user that created the record  */
  taxNumberCreatedName: Option[String],
  /* The date that the record was last updated  */
  taxNumberLastUpdated: Option[String],
  /* The user that last updated the record  */
  taxNumberLastUpdatedBy: Option[String],
  /* The name of the user that last updated the record  */
  taxNumberLastUpdatedName: Option[String],
  /* The actual ird/gst number. See externalDocs for validation rules. */
  taxNumberNumber: Option[String],
  /* The date from which this number is valid - keeping in mind the only way to get a new number is to become insolvent or immigrate / be born.  */
  taxNumberValidFrom: Option[String],
  /* The contact to which this IRD number is associated  */
  taxNumberContactId: Option[Double],
  /* The date until which this number is valid - keeping in mind that for income tax numbers the only way for this date to be set is to be born / fake your own death / immigrate to NZ or become insolvent.  */
  taxNumberValidTo: Option[String]
) extends ApiModel


