/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class UserGroupRecord (
  /* The list of links to navigate this collection */
  roles: Option[Seq[RoleRecord]],
  /*  */
  userGroupId: Option[Double],
  /*  */
  `type`: Option[String],
  /*  */
  lastUpdated: Option[Date],
  /*  */
  lastUpdatedBy: Option[String],
  /*  */
  lastUpdatedName: Option[String],
  /*  */
  code: Option[String],
  /*  */
  lockedYn: Option[Boolean],
  /*  */
  description: Option[String]
) extends ApiModel


